load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")
load("//tools/install:install.bzl", "install")
load("//tools:cpplint.bzl", "cpplint")


cc_binary(
    name = "test_log",
    srcs = ["test_log.cc"],
    deps = [
        "//cyber"
    ],

)